// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/PlayerController.h"
#include "arpgPlayerController.generated.h"

class UInputMappingContext;
class UUserWidget;

/**
 *  Basic PlayerController class for a third person game
 *  Manages input mappings
 */
UCLASS(abstract)
class AarpgPlayerController : public APlayerController
{
	GENERATED_BODY()
	
public:

	AarpgPlayerController();

protected:

	/** Input Mapping Contexts */
	UPROPERTY(EditAnywhere, Category ="Input|Input Mappings")
	TArray<UInputMappingContext*> DefaultMappingContexts;

	/**
	 *  The modal control scheme's own context, applied ALONGSIDE the ones above
	 *  rather than instead of them.
	 *
	 *  Separate on purpose: the sticks belong to the template's IMC_Default and
	 *  are not modal at all, so duplicating them here would give the stick
	 *  layout two sources of truth. Generated by Tools/generate_input_assets.py.
	 *
	 *  Soft, and defaulted in the constructor, so a fresh checkout has working
	 *  controls without anyone editing a Blueprint first -- the same convention
	 *  the character uses for its default attack tree.
	 */
	UPROPERTY(EditAnywhere, Category ="Input|Input Mappings")
	TSoftObjectPtr<UInputMappingContext> ModalMappingContext;

	/** Input Mapping Contexts */
	UPROPERTY(EditAnywhere, Category="Input|Input Mappings")
	TArray<UInputMappingContext*> MobileExcludedMappingContexts;

	/** Mobile controls widget to spawn */
	UPROPERTY(EditAnywhere, Category="Input|Touch Controls")
	TSubclassOf<UUserWidget> MobileControlsWidgetClass;

	/** Pointer to the mobile controls widget */
	UPROPERTY()
	TObjectPtr<UUserWidget> MobileControlsWidget;

	/**
	 *  The gameplay HUD.
	 *
	 *  Soft and defaulted in the constructor, like the modal input context: a
	 *  fresh checkout shows a HUD without anyone wiring one up. Clear it to run
	 *  without one, or point it at your own.
	 */
	UPROPERTY(EditAnywhere, Category = "UI")
	TSoftClassPtr<UUserWidget> HudWidgetClass;

	UPROPERTY(Transient)
	TObjectPtr<UUserWidget> HudWidget;

	/** If true, the player will use UMG touch controls even if not playing on mobile platforms */
	UPROPERTY(EditAnywhere, Config, Category = "Input|Touch Controls")
	bool bForceTouchControls = false;

	/** Gameplay initialization */
	virtual void BeginPlay() override;

	/** Input mapping context setup */
	virtual void SetupInputComponent() override;

	/** Returns true if the player should use UMG touch controls */
	bool ShouldUseTouchControls() const;

};
